default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_39720_development

test:
  <<: *default
  database: furima_39720_test

production:
  <<: *default
  database: furima_39720_production
  username: furima_39720
  password: <%= ENV["FURIMA_39720_DATABASE_PASSWORD"] %>
